version: "3.9"
services:
  django:
    build: .
    env_file:
      - .env
    volumes:
      - app-data:/app
    entrypoint: "./run.sh"
    networks:
      - nginx_network

  nginx:
    image: nginx:1.23.3
    ports:
      - "8000:80"
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - app-data:/data
    depends_on:
      - django
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  app-data:
    driver: local