version: "3.9"
services:
  django-app:
    build: .
    env_file:
      - .env
    volumes:
      - app-data:/app
    networks:
      - nginx_network

  nginx:
    image: nginx:1.23.3
    ports:
      - "${DJANGO_PORT}:80"
    volumes:
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - app-data:/data
    depends_on:
      - django-app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge

volumes:
  app-data:
    driver: local